### ISSUE TITLE
add LiteralInfinityExpression node to represent infinity literals

### ISSUE THREAD

**Issue by michaelficarra** [shapesecurity/shift-spec#13]
We currently have no way to represent `2e308`, an infinity literal. We restrict the value of a LiteralNumericExpression to be non-negative, non-NaN, and finite. SpiderMonkey Literal nodes allow an infinity value, but they do not serialise to JSON.

**Comment by jamiebuilds** [comment]
@michaelficarra Q: Why isn't `Infinity` treated like an `IdentifierExpression`, but `undefined` is?

```js
function f(Infinity) {
  console.log(Infinity);
}

f(42); // log: 42
```

**Comment by bakkot** [comment]
@thejameskyle `Infinity` *is* treated like an `IdentifierExpression` - check [here](http://shift-ast.org/parser.html?type=Script&code=function%20f(Infinity)%20%7B%0A%20%20console.log(Infinity)%3B%0A%7D%0A%0Af(42)%3B%20%2F%2F%20log%3A%2042). `LiteralInfinityExpression` from this issue is instead for numeric constants like `2e308` which have no representation as `LiteralNumericExpression` (which are, per above, non-negative, non-NaN, and finite).
